#!/bin/bash

# Set decoration geometry
berryc border_width       7
berryc inner_border_width 2
berryc title_height       0
berryc top_gap            0

# Set decoration colors
berryc focus_color         202020
berryc unfocus_color       202020
rerryc inner_focus_color   7A5954
berryc inner_unfocus_color 393939
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Iosevka Term Slab-10"
