#! /bin/sh
#
# X11 Startup File

dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

# actual programs
hsetroot -solid '#dddddd'
picom -b --config ~/etc/picom/picom.conf &
sxhkd -c ~/etc/sxhkd/sxhkdrc &

# Start a WM
exec openbox
