#!/bin/sh
#autostart file

#dbus
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

#repeat rate
xset r rate 250 50

#wallpaper
hsetroot -cover "$HOME/med/wlp/desert.jpg"

#important things
picom -b --config "$HOME/etc/picom/picom.conf"
sxhkd -c "$HOME/etc/picom/picom.conf"

#rm daemon
ch &

#choose your WM
exec openbox
#exec glazier
