#! /bin/sh

dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

# actual programs
hsetroot -cover ~/usr/pic/wallpapers/74.jpg
picom -b --config ~/etc/picom/picom.conf &
sxhkd -c ~/etc/sxhkd/sxhkdrc &
dunst -conf ~/etc/dunst/dunstrc &

# Start a WM
# exec sowm
exec openbox
